apps/adopcion/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from apps.adopcion.views import index, SolicitudList, SolicitudCreate, SolicitudUpdate, \
                                SolicitudDelete

urlpatterns = [
    url(r'^$', login_required(index), name="index"),
    url(r'^solicitud/listar', login_required(SolicitudList.as_view()), name='solicitud_listar'),
    url(r'^solicitud/nueva$', login_required(SolicitudCreate.as_view()), name='solicitud_crear'),
    url(r'^solicitud/editar/(?P<pk>\d+)$', login_required(SolicitudUpdate.as_view()), name='solicitud_editar'),
    url(r'^solicitud/eliminar/(?P<pk>\d+)$', login_required(SolicitudDelete.as_view()), name='solicitud_eliminar'),

]

refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, \
                                        password_reset_confirm, password_reset_complete
from refugio import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('apps.mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include('apps.adopcion.urls', namespace="adopcion")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),

    url(r'^$', login, {'template_name' : 'index.html'}, name="index"),
    url(r'^accounts/login/', login, {'template_name' : 'index.html'}, name="login"),
    url(r'^logout/$', logout_then_login, name='logout'),

    url(r'^reset/password_reset', password_reset, {'template_name':'usuario/password_reset/password_reset_form.html',
        'email_template_name':'usuario/password_reset/password_reset_email.html'}, name="password_reset"),

    url(r'^password_reset_done', password_reset_done,
        {'template_name':'usuario/password_reset/password_reset_done.html'}, name="password_reset_done"),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name':'usuario/password_reset/password_reset_confirm.html'}, name="password_reset_confirm"),

    url(r'^reset/complete', password_reset_complete,
        {'template_name':'usuario/password_reset/password_reset_complete.html'}, name="password_reset_complete"),

]

apps/adopcion/models.py
from __future__ import unicode_literals

from django.db import models

class Persona(models.Model):
	nombre = models.CharField(max_length=50)
	apellidos = models.CharField(max_length=70)
	edad = models.IntegerField()
	telefono = models.CharField(max_length=13)
	email = models.EmailField()
	domicilio = models.TextField()

	def __str__(self):
		return '{} {}'.format(self.nombre, self.apellidos)


class Solicitud(models.Model):
	persona = models.ForeignKey(Persona, null=True, blank=True)
	numero_mascota = models.IntegerField()
	razones = models.TextField()
		

apps/adopcion/forms.py
from django import forms

from apps.adopcion.models import Persona, Solicitud

class PersonaForm(forms.ModelForm):

	class Meta:
		model = Persona

		fields = [
			'nombre',
			'apellidos',
			'edad',
			'telefono',
			'email',
			'domicilio',
		]
		labels = {
			'nombre': 'Nombre',
			'apellidos': 'Apellidos',
			'edad': 'Edad',
			'telefono': 'Telefono',
			'email': 'Correo electronico',
			'domicilio': 'Direccion Domicilio',
		}
		widgets = {
			'nombre': forms.TextInput(),
			'apellidos': forms.TextInput(),
			'edad': forms.NumberInput(),
			'telefono': forms.NumberInput(),
			'email': forms.EmailInput(),
			'domicilio': forms.Textarea(attrs={'rows': '1', 'class':'materialize-textarea'}),
		}


class SolicitudForm(forms.ModelForm):

	class Meta :
		model = Solicitud

		fields = [
			'numero_mascota',
			'razones',
		]
		labels = {
			'numero_mascota': 'Numero de Mascotas',
			'razones': 'Razones para adoptar',
		}
		widgets = {
			'numero_mascota': forms.NumberInput(),
			'razones': forms.Textarea(attrs={'rows': '5', 'class':'materialize-textarea'}),
		}

apps/adopcion/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

from apps.adopcion.models import Persona, Solicitud
from apps.adopcion.forms import PersonaForm, SolicitudForm

def index(request):
	return HttpResponse('adopcion/index.html')


class SolicitudList(ListView):
	model = Solicitud
	template_name = 'adopcion/solicitud_list.html'
	paginate_by = 3

class SolicitudCreate(CreateView):
	model = Solicitud
	template_name = 'adopcion/solicitud_form.html'
	form_class = SolicitudForm
	second_form_class = PersonaForm
	success_url = reverse_lazy('adopcion:solicitud_listar')

	def get_context_data(self, **kwargs):
		context = super(SolicitudCreate, self).get_context_data(**kwargs)
		if 'form' not in context:
			context['form'] = self.form_class(self.request.GET)
		if 'form2' not in context :
			context['form2'] = self.second_form_class(self.request.GET)
		return context

	def post(self, request, *args, **kwargs):
		self.object = self.get_object
		form = self.form_class(request.POST)
		form2 = self.second_form_class(request.POST)
		if form.is_valid() and form2.is_valid():
			solicitud = form.save(commit=False)
			solicitud.persona = form2.save()
			solicitud.save()
			return HttpResponseRedirect(self.get_success_url())
		else:
			return self.render_to_response(self.get_context_data(form=form, form2=form2))


class SolicitudUpdate(UpdateView):
	model = Solicitud
	second_model = Persona
	template_name = 'adopcion/solicitud_form.html'
	form_class = SolicitudForm
	second_form_class = PersonaForm
	success_url = reverse_lazy('adopcion:solicitud_listar')

	def get_context_data(self, **kwargs):
		context = super(SolicitudUpdate, self).get_context_data(**kwargs)
		pk = self.kwargs.get('pk', 0)
		solicitud = self.model.objects.get(id=pk)
		persona = self.second_model.objects.get(id=solicitud.persona_id)

		if 'form' not in context:
			context['form'] = self.form_class()
		if 'form2' not in context :
			context['form2'] = self.second_form_class(instance=persona)
		context['id'] = pk
		return context

	def post(self, request, *args, **kwargs):
		self.object = self.get_object
		id_solicitud = kwargs['pk']
		solicitud = self.model.objects.get(id=id_solicitud)
		persona = self.second_model.objects.get(id=solicitud.persona.id)

		form = self.form_class(request.POST, instance=solicitud)
		form2 = self.second_form_class(request.POST, instance=persona)

		if form.is_valid() and form2.is_valid():
			form.save()
			form2.save()
			return HttpResponseRedirect(self.get_success_url())
		else:
			return HttpResponseRedirect(self.get_success_url())


class SolicitudDelete(DeleteView):
	model = Solicitud
	template_name = 'adopcion/solicitud_delete.html'
	success_url = reverse_lazy('adopcion:solicitud_listar')

templates/adopcion/solicitud_delete.html
{% extends 'base/base.html' %}

{% block title %} Eliminar Solicitud {% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col hide-on-small-only offset-l2"></div>
			<div class="col m12 l8">
				<div class="card-panel grey lighten-4 hoverable z-depth-4">
					<form method="post">
						{% csrf_token %}
						<center>
							<big>¿Desea eliminar  el registro de {{ object.persona.nombre }}?</big>
								<br><br>
							<a href="{% url 'adopcion:solicitud_listar' %}" class="btn white black-text">Cancelar</a>
							<button type="submit" class="btn waves-effect red">Eliminar</button>
						</center>
					</form>

				</div>
			</div>
		</div>
	</div>

{% endblock %}

templates/adopcion/solicitud_form.html
{% extends 'base/base.html' %}

{% block title %} Formulario Solicitud {% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<!-- <div class="col hide-on-small-only offset-l2"></div> -->
			<div class="col m12">
				<div class="card-panel grey lighten-4 hoverable z-depth-4">
					<form method="post">
						{% csrf_token %}
						<div class="row">
							<div class="col s12 l6">
								<div class="center">Datos de la Persona</div>
								<div class="row">
									<div class="input-field col s12 m6">
										{{ form2.nombre }}
										<label for="{{ form2.nombre.label }}">{{ form2.nombre.label }}</label>
									</div>
									<div class="input-field col s12 m6">
										{{ form2.apellidos }}
										<label for="{{ form2.apellidos.label }}">{{ form2.apellidos.label }}</label>
									</div>
									<div class="input-field col s12 m6">
										{{ form2.edad }}
										<label for="{{ form2.edad.label }}">{{ form2.edad.label }}</label>
									</div>
									<div class="input-field col s12 m6">
										{{ form2.telefono }}
										<label for="{{ form2.telefono.label }}">{{ form2.telefono.label }}</label>
									</div>
									<div class="input-field col s12">
										{{ form2.email }}
										<label for="{{ form2.email.label }}">{{ form2.email.label }}</label>
									</div>
									<div class="input-field col s12">
										{{ form2.domicilio }}
										<label for="{{ form2.domicilio.label }}">{{ form2.domicilio.label }}</label>
									</div>
								</div>
							</div>
							<div class="col hide-on-med-and-down l1"></div>
							<div class="col s12 l5">
								<div class="center">Datos de Adopción</div>
								<div class="input-field">
									{{ form.numero_mascota }}
									<label for="{{ form.numero_mascota.label }}">{{ form.numero_mascota.label }}</label>
								</div>
								<div class="input-field">
									{{ form.razones }}
									<label for="{{ form.razones.label }}">{{ form.razones.label }}</label>
								</div>
							</div>
						</div>
						<center>
							<button type="submit" class="btn waves-effect">Guardar</button>
						</center>
					</form>

				</div>
			</div>
		</div>
	</div>

{% endblock %}

{% block extrajs %}
	<script type="text/javascript">
		$(document).ready(function(){
			// $('textarea').addClass('materialize-textarea');
			$('#id_razones').trigger('autoresize');
		});
	</script>
{% endblock %}

templates/adopcion/solicitud_list.html
{% extends 'base/base.html' %}

{% block title %} Listado de Solicitudes {% endblock %}

{% block content %}
<div class="container">
	<div class="card-panel z-depth-4">
		<center>
			<p class="flow-text titulo-tabla">Listado de Solicitudes de Adopción</p>
		</center>

		<table class="striped responsive-table">
			<thead>
				<tr>
					<td>No. Solicitante</td>
					<td>Adoptante</td>
					<td>No. Mascotas</td>
					<td>Razones</td>
					<td>Acciones</td>
				</tr>
			</thead>
			<tbody>
				{% if object_list %}
					{% for solicitud in object_list %}
						<tr>
							<td>{{ solicitud.id }}</td>
							<td>{{ solicitud.persona.nombre }} {{ solicitud.persona.apellidos }}</td>
							<td>{{ solicitud.numero_mascota }}</td>
							<td>{{ solicitud.razones }}</td>
							<td>
								<a href="{% url 'adopcion:solicitud_editar' solicitud.id %}" class="btn waves-effect">
									<i class="far fa-edit"></i>  <span class="hide-on-med-and-down">Editar</span>
								</a>
								<a href="{% url 'adopcion:solicitud_eliminar' solicitud.id %}" class="btn waves-effect red">
									<span class="hide-on-med-and-down">Eliminar</span>  <i class="far fa-trash-alt"></i>
								</a>
							</td>
						</tr>
					{% endfor %}
				{% else %}
					<h4>No hay registro de solicitudes :(</h4>
				{% endif %}

			</tbody>
		</table>

		<br>
		<div class="row center">
			<a href="{% url 'adopcion:solicitud_crear' %}" class="btn waves-effect blue">Crear Solicitud <i class="fas fa-plus"></i></a>
		</div>
		<div class="center">
			 <ul class="pagination">
				{% if page_obj.has_previous %}
					<a href="?page={{page_obj.previous_page_number}}" class="btn waves-effect waves-light btn-rounded"><i class="fas fa-arrow-left"></i> Anterior</a>
				{% endif %}
				{% if page_obj.has_next %}
					<a href="?page={{page_obj.next_page_number}}" class="btn waves-effect waves-light btn-rounded">Siguente <i class="fas fa-arrow-right"></i></a>
				{% endif %}
			</ul>
		</div>

	</div>
</div>

{% endblock %}