apps/adopcion/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from apps.adopcion.views import index, SolicitudList, SolicitudCreate, SolicitudUpdate, \
                                SolicitudDelete

urlpatterns = [
    url(r'^$', login_required(index), name="index"),
    url(r'^solicitud/listar', login_required(SolicitudList.as_view()), name='solicitud_listar'),
    url(r'^solicitud/nueva$', login_required(SolicitudCreate.as_view()), name='solicitud_crear'),
    url(r'^solicitud/editar/(?P<pk>\d+)$', login_required(SolicitudUpdate.as_view()), name='solicitud_editar'),
    url(r'^solicitud/eliminar/(?P<pk>\d+)$', login_required(SolicitudDelete.as_view()), name='solicitud_eliminar'),

]

apps/mascota/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from apps.mascota.views import index, mascota_view, mascota_list, mascota_edit, \
            mascota_delete, MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete


urlpatterns = [
    url(r'^$', login_required(index), name='index'),
    # url(r'^nuevo$', mascota_view, name='mascota_crear'),
    url(r'^nuevo$', login_required(MascotaCreate.as_view()), name='mascota_crear'),
    # url(r'^listar$', mascota_list, name='mascota_listar'),
    url(r'^listar', login_required(MascotaList.as_view()), name='mascota_listar'),
    # url(r'^editar/(?P<id_mascota>\d+)/$', mascota_edit, name='mascota_editar'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(MascotaUpdate.as_view()), name='mascota_editar'),
    # url(r'^eliminar/(?P<id_mascota>\d+)/$', mascota_delete, name='mascota_eliminar'),
   	url(r'^eliminar/(?P<pk>\d+)/$', login_required(MascotaDelete.as_view()), name='mascota_eliminar'),

]

apps/usuario/urls.py
from django.conf.urls import url

from apps.usuario.views import index, RegistroUsuario

urlpatterns = [
    url(r'^$', index),
    url(r'^registrar', RegistroUsuario.as_view(), name="registrar"),

]

refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, \
                                        password_reset_confirm, password_reset_complete
from refugio import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('apps.mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include('apps.adopcion.urls', namespace="adopcion")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),

    url(r'^$', login, {'template_name' : 'index.html'}, name="index"),
    url(r'^accounts/login/', login, {'template_name' : 'index.html'}, name="login"),
    url(r'^logout/$', logout_then_login, name='logout'),

    url(r'^reset/password_reset', password_reset, {'template_name':'usuario/password_reset/password_reset_form.html',
        'email_template_name':'usuario/password_reset/password_reset_email.html'}, name="password_reset"),

    url(r'^password_reset_done', password_reset_done,
        {'template_name':'usuario/password_reset/password_reset_done.html'}, name="password_reset_done"),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name':'usuario/password_reset/password_reset_confirm.html'}, name="password_reset_confirm"),

    url(r'^reset/complete', password_reset_complete,
        {'template_name':'usuario/password_reset/password_reset_complete.html'}, name="password_reset_complete"),

]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %} {% endblock %} - Refugio de Animales</title>

	<link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/myStyles.css' %}">

	<script type="text/javascript" src="{% static 'js/fontawesome-all.js' %}"></script>

	{% block extrahead %}
	{% endblock %}
</head>
<body class="teal">
	{% block header %}
		{% include 'base/header.html' %}
		{% include 'base/sidenav.html' %}
		<br>
	{% endblock %}

	<main>
		{% block content %}
			<h4>Soy el content</h4>
		{% endblock %}
	</main>

	{% block footer %}
		<br><br>
		{% include 'base/footer.html' %}
	{% endblock %}

	<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/myScript.js' %}"></script>

	{% block extrajs %}
	{% endblock %}

</body>
</html>

templates/base/footer.html
<footer class="page-footer teal darken-2">
	<div class="container">
		<div class="row">
			<div class="hide-on-small-only col offset-m2 offset-l4"></div>
			<div class="col s12 m10 l4 center-align">
				<h4>Power By</h4>
				<a class="white-text" href="http://github.com/samir04m"><i class="fab fa-github fa-2x"></i> <big>Samir Mejia</big></a>
			</div>
		</div>
	</div>
	<div class="footer-copyright">
		<div class="container">
			<span class="white-text">© 2018 Copyright</span>
			<a href="http://materializecss.com" class="right white-text">Materialize</a>
		</div>
	</div>
</footer>

templates/base/header.html
<header>
	<ul id="drop-account" class="dropdown-content">
	  <li><a href="#!"><i class="fas fa-cogs"></i> Ajustes</a></li>
	  <li class="divider"></li>
	  <li><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Cerrar Sesión</a></li>
	</ul>
	<nav class="teal darken-2">
		<div class="container">
			<div class="nav-wrapper">
				{% if request.user.is_authenticated %}
					<a href="{% url 'mascota:mascota_listar' %}" class="brand-logo truncate hide-on-small-only"><i class="fas fa-paw"></i> Refugio de Animales</a>
				{% else %}
					<a href="{% url 'index' %}" class="brand-logo truncate hide-on-small-only"><i class="fas fa-paw"></i> Refugio de Animales</a>
				{% endif %}
				<a href="#" class="button-collapse" data-activates="slide-out">
					<i class="fas fa-bars fa-lg"></i>
				</a>

				<ul class="right hide-on-med-and-down">
					{% if request.user.is_authenticated %}
						<li><a href="{% url 'mascota:mascota_listar' %}">Mascotas</a></li>
						<li><a href="{% url 'adopcion:solicitud_listar' %}">Adopciones</a></li>
						<li><a href="#!" class="dropdown-button" data-activates="drop-account">
							<i class="fas fa-user-circle"></i>
							{{request.user.username }} <i class="fas fa-angle-down"></i>
						</a></li>
					{% else %}
						<li><a href="{% url 'usuario:registrar' %}">Registro</a></li>
						<li><a href="{% url 'login' %}">Ingresar</a></li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav>
</header>

templates/base/sidenav.html
{% load staticfiles %}
<ul id="slide-out" class="side-nav">
    {% if request.user.is_authenticated %}
          <li><div class="user-view">
                <div class="background">
                  <img src="{% static 'images/office.jpg' %}">
                </div>
                <a href="#!user"><img class="circle" src="{% static 'images/yuna.jpg' %}"></a>
                <a href="#!name"><span class="white-text name">{{request.user.first_name}} {{request.user.last_name}}</span></a>
                <a href="#!email"><span class="white-text email">{{request.user.email}}</span></a>
          </div></li>
          <li><a href="{% url 'mascota:mascota_listar' %}">Mascotas</a></li>
          <li><a href="{% url 'adopcion:solicitud_listar' %}">Adopciones</a></li>

          <li class="no-padding">
                <ul class="collapsible collapsible-accordion">
                      <li>
                        <a class="collapsible-header">
                            <i class="fas fa-user-circle"></i>
                            {{request.user.username }} <i class="fas fa-angle-down"></i>
                        </a>
                        <div class="collapsible-body">
                          <ul>
                                <li><a href="#!"><i class="fas fa-cogs"></i> Ajustes</a></li>
                                <li class="divider"></li>
                                <li><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Cerrar Sesión</a></li>
                          </ul>
                        </div>
                      </li>
                </ul>
          </li>
      {% else %}
          <li><a href="{% url 'usuario:registrar' %}">Registro</a></li>
          <li><a href="{% url 'login' %}">Ingresar</a></li>
      {% endif %}
</ul>