apps/mascota/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from apps.mascota.views import index, mascota_view, mascota_list, mascota_edit, \
            mascota_delete, MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete


urlpatterns = [
    url(r'^$', login_required(index), name='index'),
    # url(r'^nuevo$', mascota_view, name='mascota_crear'),
    url(r'^nuevo$', login_required(MascotaCreate.as_view()), name='mascota_crear'),
    # url(r'^listar$', mascota_list, name='mascota_listar'),
    url(r'^listar', login_required(MascotaList.as_view()), name='mascota_listar'),
    # url(r'^editar/(?P<id_mascota>\d+)/$', mascota_edit, name='mascota_editar'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(MascotaUpdate.as_view()), name='mascota_editar'),
    # url(r'^eliminar/(?P<id_mascota>\d+)/$', mascota_delete, name='mascota_eliminar'),
   	url(r'^eliminar/(?P<pk>\d+)/$', login_required(MascotaDelete.as_view()), name='mascota_eliminar'),

]

refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, \
                                        password_reset_confirm, password_reset_complete
from refugio import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('apps.mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include('apps.adopcion.urls', namespace="adopcion")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),

    url(r'^$', login, {'template_name' : 'index.html'}, name="index"),
    url(r'^accounts/login/', login, {'template_name' : 'index.html'}, name="login"),
    url(r'^logout/$', logout_then_login, name='logout'),

    url(r'^reset/password_reset', password_reset, {'template_name':'usuario/password_reset/password_reset_form.html',
        'email_template_name':'usuario/password_reset/password_reset_email.html'}, name="password_reset"),

    url(r'^password_reset_done', password_reset_done,
        {'template_name':'usuario/password_reset/password_reset_done.html'}, name="password_reset_done"),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name':'usuario/password_reset/password_reset_confirm.html'}, name="password_reset_confirm"),

    url(r'^reset/complete', password_reset_complete,
        {'template_name':'usuario/password_reset/password_reset_complete.html'}, name="password_reset_complete"),

]

apps/mascota/models.py
from __future__ import unicode_literals

from django.db import models

from apps.adopcion.models import Persona


class Vacuna(models.Model):
	nombre = models.CharField(max_length=50)

	def __str__(self):
		return '{}'.format(self.nombre)


class Mascota(models.Model):
	nombre = models.CharField(max_length=50)
	sexo = models.CharField(max_length=10)
	edad_aproximada = models.IntegerField()
	fecha_rescate = models.DateField()

	persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
	vacuna = models.ManyToManyField(Vacuna, blank=True)

apps/mascota/forms.py
from django import forms

from apps.mascota.models import Mascota

class MascotaForm(forms.ModelForm):

	class Meta:
		model = Mascota

		fields = [
			'nombre',
			'sexo',
			'edad_aproximada',
			'fecha_rescate',
			'persona',
			'vacuna',
		]

		labels = {
			'nombre': 'Nombre',
			'sexo': 'Sexo',
			'edad_aproximada': 'Edad Aproximada',
			'fecha_rescate': 'Fecha de rescate', 
			'persona': 'Adoptante',
			'vacuna': 'Vacunas',
		}

		widgets = {
			'nombre': forms.TextInput(),
			'sexo': forms.TextInput(),
			'edad_aproximada': forms.TextInput(),
			'fecha_rescate': forms.TextInput(), 
			'persona': forms.Select(),
			'vacuna': forms.SelectMultiple(),
		}

apps/mascota/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect

# Create your views here.

from django.http import HttpResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

from apps.mascota.forms import MascotaForm
from apps.mascota.models import Mascota

def index(request):
	return render(request, 'mascota/index.html')

def mascota_view(request):
	if request.method == 'POST':
		form = MascotaForm(request.POST)
		if form.is_valid() :
			form.save()
		return redirect('mascota:mascota_listar')
	else:
		form = MascotaForm()

	return render(request, 'mascota/mascota_form.html', {'form':form})


def mascota_list(request):
	mascotas = Mascota.objects.all().order_by('id')
	contexto = {"mascotas": mascotas}
	return render(request, 'mascota/mascota_list.html', contexto)


def mascota_edit(request, id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == 'GET':
		form = MascotaForm(instance=mascota)
	else:
		form = MascotaForm(request.POST, instance=mascota)
		if form.is_valid() :
			form.save()
		return redirect('mascota:mascota_listar')

	return render(request, 'mascota/mascota_form.html', {'form':form})


def mascota_delete(request, id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == 'POST':
		mascota.delete()
		return redirect("mascota:mascota_listar")

	return render(request, 'mascota/mascota_delete.html', {'mascota':mascota})


class MascotaList(ListView):
	model = Mascota
	template_name = 'mascota/mascota_list.html'
	paginate_by = 2

class MascotaCreate(CreateView):
	model = Mascota
	form_class = MascotaForm
	template_name = 'mascota/mascota_form.html'
	success_url = reverse_lazy('mascota:mascota_listar')

class MascotaUpdate(UpdateView):
	model = Mascota
	form_class = MascotaForm
	template_name = 'mascota/mascota_form.html'
	success_url = reverse_lazy('mascota:mascota_listar')


class MascotaDelete(DeleteView):
	model = Mascota
	template_name = 'mascota/mascota_delete.html'
	success_url = reverse_lazy('mascota:mascota_listar')

templates/mascota/index.html
{% extends 'base/base.html' %}

{% block title %}
	Inicio Mascota
{% endblock %}

{% block content %}
	<div class="container">
		
	</div>
{% endblock %}

templates/mascota/mascota_delete.html
{% extends 'base/base.html' %}

{% block title %} Eliminar una Mascota {% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col hide-on-small-only offset-l2"></div>
			<div class="col m12 l8">
				<div class="card-panel grey lighten-4 hoverable z-depth-4">
					<form method="post">
						{% csrf_token %}
						<center>
							<big>¿Desea eliminar  el registro de {{ object.nombre }}?</big>
								<br><br>
							<a href="{% url 'mascota:mascota_listar' %}" class="btn white black-text">Cancelar</a>
							<button type="submit" class="btn waves-effect red">Eliminar</button>
						</center>
					</form>
					
				</div>
			</div>
		</div>
	</div>

{% endblock %}

templates/mascota/mascota_form.html
{% extends 'base/base.html' %}

{% block title %} Crear una Mascota {% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col hide-on-small-only offset-l2"></div>
			<div class="col m12 l8">
				<div class="card-panel grey lighten-4 hoverable z-depth-4">
					<form method="post">
						{% csrf_token %}
						{{ form.as_p }}
						<button type="submit" class="btn waves-effect">Guardar</button>
					</form>
					
				</div>
			</div>
		</div>
	</div>

{% endblock %}

templates/mascota/mascota_list.html
{% extends 'base/base.html' %}

{% block title %} Listado de Mascotas {% endblock %}

{% block content %}
<div class="container">
	<div class="card-panel z-depth-4">
		<center>
			<p class="flow-text titulo-tabla">Listado de Mascotas</p>
		</center>

		<table class="striped centered responsive-table">
			<thead>
				<tr>
					<td>#</td>
					<td>Nombre</td>
					<td>Sexo</td>
					<td>Edad</td>
					<td>Fecha de Rescate</td>
					<td>Adoptante</td>
					<td>Acciones</td>
				</tr>
			</thead>
			<tbody>
				{% if object_list %}
					{% for mascota in object_list %}
						<tr>
							<td>{{ mascota.id }}</td>
							<td>{{ mascota.nombre }}</td>
							<td>{{ mascota.sexo }}</td>
							<td>{{ mascota.edad_aproximada }}</td>
							<td>{{ mascota.fecha_rescate }}</td>
							<td>{{ mascota.persona.nombre }} {{ mascota.persona.apellidos }}</td>
							<td>
								<a href="{% url 'mascota:mascota_editar' mascota.id %}" class="btn waves-effect">
									<i class="far fa-edit"></i> <span class="hide-on-med-and-down">Editar</span>
								</a>
								<a href="{% url 'mascota:mascota_eliminar' mascota.id %}" class="btn waves-effect red">
									<span class="hide-on-med-and-down">Eliminar</span> <i class="far fa-trash-alt"></i>
								</a>
							</td>
						</tr>
					{% endfor %}
				{% else %}
					<h4>No hay registro de mascotas :(</h4>
				{% endif %}

			</tbody>
		</table>

		<br>
		<div class="row center">
			<a href="{% url 'mascota:mascota_crear' %}" class="btn waves-effect blue">Agregar Mascota <i class="fas fa-plus"></i></a>
		</div>
		<div class="center">
			 <ul class="pagination">
				{% if page_obj.has_previous %}
					<a href="?page={{page_obj.previous_page_number}}" class="btn waves-effect waves-light btn-rounded"><i class="fas fa-arrow-left"></i> Anterior</a>
				{% endif %}
				{% if page_obj.has_next %}
					<a href="?page={{page_obj.next_page_number}}" class="btn waves-effect waves-light btn-rounded">Siguente <i class="fas fa-arrow-right"></i></a>
				{% endif %}
			</ul>
		</div>
	</div>
</div>

{% endblock %}